
CREATE TABLE IF NOT EXISTS `cruzNahual` (
  `idCruz` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `nahual` varchar(15) NOT NULL,
  `concepcion` varchar(15) NOT NULL,
  `derecho` varchar(15) NOT NULL,
  `izquierdo` varchar(15) NOT NULL,
  `destino` varchar(15) NOT NULL,
  `descripcion` longtext NOT NULL,
  `categoria` varchar(100) NOT NULL,
  KEY `fk_cruz_categoria1_idx` (`categoria`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `cruzNahual`
  ADD CONSTRAINT `fk_cruz_categoria1` FOREIGN KEY (`categoria`) REFERENCES `categoria` (`nombre`);


INSERT INTO `cruzNahual` (`nahual`,`concepcion`,`derecho`,`izquierdo`,`destino`,`descripcion`, `categoria`) VALUES 
("B'atz'", "Aq'ab'al", "Kan", "No'j", "Kawoq", "La persona nacida ante el día B'atz' fue engendrada en AQ'AB'AL, su destino es regido por el día KAWOQ'. El Pop Wuj, (libro sagrado Maya) dice: Que los primeros gemelos divinos fueron Jun B'atz' y Jun Chuwen, hermanos mayores de Jun Ajpu e Ixb'alamke, quienes fueron vencidos por su egoísmo y su soberbia. Jun B'atz' y Jun Chuwen, grandes sabios, se convirtieron en monos, *«por soberbios y por maltratar a sus hermanos menores» Junajpu e Ixb'alamke, por prodigio de ellos fueron vencidos.\nLa energía de su concepción, AQ'AB'AL, le da un interés especial por el pasado y una visión futurista. Su mayor problema será ubicarse en el presente. Tiene un desarrollo espiritual.\nEl KAN, en su lado derecho, le da una fuerza extra. La energía y el fuego interno serán su mayor prueba. Su mano derecha obrará muchas curaciones.\nEl NOJ', en su lado izquierdo, le da nobleza al conocimiento adquirido a lo largo de la vida que se tornará en sabiduría. Posee una fuerte tendencia a lo espiritual.\nLa energía de su destino, KAWOQ, orienta la persona hacia la comunidad. El tema de la familia le acompañará toda la vida.", "cruz01"),
("Be'e", "K'at", "Keme", "Tijax", "Ajpu", "La Cruz Maya de persona nacida ante el BE’E fue engendrada en el día K’At y su destino lo rige el AJPU. Será un excelente comerciante e intermediario.\nEl K'at es responsable de los enredos que le pone la vida.\nEl Keme denota un alma antigua con inclinación al pasado, a lo ancestral. Será respetado en la edad mayor. Esta energía le protege de la muerte en accidentes y enfermedades. Buena comunicación con sus antepasados y otras dimensiones.\nEl Tijax lo protege de los engañadores y le indica cuando retirarse en una situación negativa. Lo favorece no solo en el plano material, sino también en el plano espiritual. Puede hacer decisiones impulsivas.\nEl destino Ajpu le da seguridad y estabilidad, le ayudará a realizar sus propósitos y logrará vencer los obstáculos y pruebas que la vida le pone.", "cruz02"),
("Aj", "Kan", "Kiej", "Kawoq", "Imox", "La persona nacida ante el AJ es engendrada en el día KAN y su destino lo rige IMOX. Representación de la autoridad, a lo largo de la vida se le reconoce como un experto en su campo.\nLa energia de su concepcion Kan le brinda una fuerza extra, inagotable; tiene mucha energía, por lo que es muy deseado o rechazado. La autodisciplina es su mejor aliada para canalizar su energía. Una eterna búsqueda del conocimiento.\nEl Kej le da inspiración e imaginación, le da sensibilidad hacia el arte, en especial la música y la pintura.\nEl Kawoq en su lado izquierdo, influye a que planifique en grande, a buscar el bienestar común y la justicia social.\nSu signo de destino es Imox, hace que su vida se vea enriquecida por experiencias fuera de lo común. Le da una especial propensión hacia el misticismo. Inconformidad hacia lo establecido.", "cruz03"),
("I'x", "Keme", "Q'anil", "Ajpu", "Iq'", "La persona nacida ante el I’X es engendrada en el día KEME y su destino lo rige el IQ’. Signo de grandes místicos, poderosos magos, los primeros padres de la presente humanidad rigen este signo. Cazador nato, siempre está atento y trata de evitar el peligro.\nEl Keme, a la concepción, le hará sentir una atracción hacia lo antiguo y le permite una exitosa búsqueda interior. Extraordinaria intuición.\nEl Q'anil, en su lado derecho, lo orienta para ser un gran sembrador, todo lo que siembre tendrá frutos.\nEl Ajpu, en su lado izquierdo, vencerá las pruebas, especialmente las de índole espiritual y le dará certeza, seguridad y fuerza para alcanzar sus metas. La persona necesita que le reconozcan sus logros.\nEl Iq', como signo del destino, alimenta su imaginación y pensamientos dando una inteligencia especial.", "cruz04"),
("Tz'ikin", "Kiej", "Toj", "Imox", "Aq'ab'al", "La persona nacida ante el TZ’IKIN es engendrada en el día KEJ y su destino lo rige el AQ’AB’AL. Su extraordinaria intuición le salvará de muchos problemas. Su naturaleza es la independencia, la libertad de las aves. Se ilusionan y desilusionan rápido de lo que llaman su atención.\nEl Kej, a la concepción, lo hace necesitar y amar la naturaleza; se acomoda muy bien en toda situación y lugar que les toque vivir.\nEl Toj, en su lado derecho, le da calidez humana, el contacto con el fuego es importante para su armonía y equilibrio.\nEl Imox, en su lado izquierdo, le marca lo inesperado, orienta su vida hacia el misticismo, dándole fuerza y capacidad para desarrollar sus sentidos y fuerza interna.\nEl Aq'ab'al, como energía del destino, le orienta a buscar en el pasado las respuestas, y también a todo lo nuevo, a la tecnología. Este signo le dará una apariencia juvenil.", "cruz05"),
("Ajmaq", "Q'anil", "Tz'i'", "Iq'", "K'at", "La persona nacida ante Ajmaq es engendrada en el día Q’ANIL y su destino lo rige el día K’AT. Buena dosis de curiosidad. Su dilema es no perderse entre la ilusión del mundo material y sacar la luz interior.\nEl Q'anil, como signo de concepción, proporciona la semilla que germinará en un proyecto lento pero seguro en cualquiera de los aspectos de su vida.\nEl Tz'i', en su lado derecho, indica una tendencia a la ley material. Su mano derecha tiene el poder y la autoridad de curar toda enfermedad de origen orgánico.\nEl Iq', en su lado izquierdo, lo impulsa hacia los misterios y la espiritualidad, provocando una mente expansiva y una conciencia universal.\nEl K'at como energía del destino, le pone las pruebas y enredos. El trabajo es aprender de todos estos enredos y fuertes experiencias que le ha puesto la vida. La curiosidad del Ajmaq y la red del K´at son una alianza difícil de controlar.", "cruz06"),
("No'j", "Toj", "B'atz'", "Aq'ab'al", "Kan", "La persona nacida ante el día NO’J es engendrada en el día TOJ y su destino lo rige el KAN. Es el signo del aprendizaje, con proyección a la sabiduría; la nobleza y la extrema confianza son rasgos que marcan su vida. Su visión del mundo es idealista.\nEl Toj, en la concepción, indica un sufrimiento emocional principalmente en la niñez. Los sufrimientos o pagos que le tocan tienen allí su origen.\nEl B'atz', en su lado derecho, le da un don especial para las artes, para la medicina, la cirugía y especialmente la medicina ancestral.\nEl Aq'ab'al, en su lado izquierdo, le manifiesta muchos cambios, principalmente en lo espiritual por lo que necesita centralizar su atención en una disciplina para no dispersar sus energías. Signo renovador y cambiante. Su mayor experiencia en la vida se la dan los viajes.\nEl Kan, como signo del destino, le proporciona mucha energía. Le da el romanticismo y proporciona amores platónicos.", "cruz07"),
("Tijax", "Tz'i'", "Be'e", "K'at", "Keme", "La persona nacida ante el TIJAX es engendrada en el día TZ’I’ y su destino lo rige el día KEME. Esta energía lo hace tajante, sus decisiones pueden ser impulsivas. Debe ayudar a las personas con problemas, cortar las enfermedades, las energías negativas.\nEl Tz'i', en su concepción, le da una relación con la justicia, siendo reconocido como autoridad. Son justos pero drásticos. Experiencias extraordinarias en el campo espiritual.\nEl Be'e, en su lado derecho, le propicia buena fortuna y medios económicos para la vida. Viajes o cambio de residencia de forma intempestiva.\nEl K'at, en su lado izquierdo, le indica una vida llena de experiencias y cambios. Debe meditar su accionar para no estar atrapado en situaciones en las que los demás arreglan sus problemas.\nEl Keme, como destino, lo protege de accidentes y malas muertes, por lo que logra finalizar su propósito de existencia. Kame es la muerte, el signo de los ancestros y de la seguridad.", "cruz08"),
("Kawoq", "B'atz'", "Aj", "Kan", "Kiej", "La persona nacida ante el día KAwoq es engendrada en B’ATZ’ y su destino lo rige el día KEJ. El signo KAWOQ da una tendencia hacia lo comunitario. Signo de abundancia.\nEl B'atz', le da buena disposición como planificador y ejecutor de proyectos comunitarios, y lo acerca a la medicina tradicional.\nEl Aj, en su lado derecho, le da un carácter fuerte y autoritario, aunque en el fondo es noble y siempre busca protección.\nEl Kan, en su lado izquierdo, hace que su mente y espíritu alcancen una relación conjunta. Despierta los poderes ocultos en la persona\nEl Kej, lo marca como una persona sensitiva, ágil, nerviosa, de acciones rápidas. El signo KEJ le indica tomar precaución, pues en donde menos lo espera lo pueden traicionar. Necesita manifestaciones artísticas y tener su propio espacio, su refugio.", "cruz09"),
("Ajpu", "Be'e", "I'x", "Keme", "Q'anil", "La persona nacida ante AJPU’ es engendrada en el día BE’E y su destino lo rige Q’ANIL. Será protegida con una fuerza mayor, pero de desconocerlo será un mal elemento para la sociedad, alguien que divide, desorienta las ideas. Tiene una visión profunda que va más allá de lo superficial.\nEl Be'e, en la concepción, le depara muchos viajes, y por temporadas vivirá en el extranjero. Esta energía propicia los amores con gente extranjera.\nLa energia del I'x, en su lado derecho, le da el poder para ser buen intermediario, es la que le otorga las dotes artísticas. A los hombres da un conocimiento de la mujer. En la mujer pondrá la feminidad, la sensualidad y la astucia.\nEl Keme, en su lado izquierdo, protege la vida del nacido en Ajpu. Le proporciona una gran curiosidad, valentía y espíritu aventurero.\nEl Q'anil, le hace ser sembrador, siendo su misión señalar el camino y plantar la semilla, no necesariamente ve el fruto de sus acciones. Anda con certeza, donde llega tu convicción comenzará a fluir la energía.", "cruz10"),
("Imox", "Aj", "Tz'ikin", "Kiej", "Toj", "La persona nacida ante el día IMOX es engendrada en AJ y su destino lo rige el día TOJ. Es el signo que más rápido desarrolla los poderes paranormales; tiene una gran relación con los animales acuáticos.\nEl Aj, orienta su vida dándole orden y seriedad, pues de otra forma le daría rienda suelta a su locura.\nEl Tz'ikin, en su lado derecho, le trae suerte y fortuna en el trabajo y los negocios para vivir cómodamente. Romántico, tierno, cálido. Puede romper las relaciones en un minuto.\nEl Kej, en su lado izquierdo, le da sensibilidad, un acercamiento a la naturaleza, lo ayuda a ubicarse en toda situación y lugar. También le proporciona agilidad mental para solucionar problemas y enredos en los que se mete.\nEl Toj, le hará pagar sus desaciertos; le indica que debe hacer ofrendas de índole espiritual y material ante el gran Ajaw.", "cruz11"),
("Iq'", "I'x", "Ajmaq", "Q'anil", "Tz'i'", "La persona nacida ante el día IQ’ es engendrada en I’X y su destino lo rige el TZ’I’. El signo del IQ’ es el más sensitivo y más analítico de todos los signos.\nEl I'x, le trae comprensión y armonía con el sexo opuesto. Instinto de protección y ataque parecido al felino.\nEl Ajmaq, , en su lado derecho, le da curiosidad que bien aplicado lo hará descubrir o inventar muchas cosas. Gran energía de fuerza curativa en su mano derecha.\nEl Q'anil, que le da una sensibilidad especial para el arte, que es su mejor forma de expresión. Su crecimiento espiritual depende de su armonía con la Madre Tierra.\nEn el futuro acompañara el Tz'i', solo que a su medida hace su propia ley.", "cruz12"),
("Aq'ab'al", "Tz'ikin", "No'j", "Toj", "B'atz'", "La persona nacida ante el día AQ’AB’AL es engendrada en el día TZ’IKIN y su destino lo rige el B’ATZ’. Mucha dualidad en este signo y muchas oportunidades, su dilema será siempre escoger la correcta.\nEl Tz'ikin le trae suerte, protección, fortuna, intuición, visión y telepatía.\nEl No'j, en su lado derecho, le indica una nobleza especial, un carácter determinado y una gran capacidad intelectual. Debe descubrir su pasado para proyectarse al futuro.\nEl Toj está en su lado izquierdo. Esta energía lo hará confrontar con su balance positivo o negativo.\nEl B'atz', le propicia planificar los pasos que va a dar y no actuar impulsivamente.", "cruz13"),
("K'at", "Ajmaq", "Tijax", "Tz'i'", "Be'e", "La persona nacida ante el día K’AT es engendrada en AJMAQ y su destino lo rige el BE’E. Este signo le da a la persona una vida llena de pruebas. Por saldo de vidas pasadas, tiene un balance negativo que tendrá que limpiar con grandes oraciones y ceremonia y con labor social caritativo.\nEl Ajmaq, lo vuelve muy curioso. Esta alianza Ajmaq (curiosidad) / K’at (red) tiene un ascendente negativo sobre la persona porque le da una tendencia a quedar atrapada en los problemas debe hacer grandes oraciones y ceremonias para evitar todo lo negativo en su vida.\nEl Tijax, en su lado derecho, le da un poder que si no lo cuida se volverá incontrolable. Si aprende a usar ese poder será una persona apreciada y buscada por quienes necesiten ayuda. Es la energía que libera de los líos en que se meten, el Tijax corta la red. Puede cortar enfermedades.\nEl Tz'i' en su lado izquierdo, señala la ley. Por lo que suele ser una persona reconocida por su autoridad, aunque tiende a ser autoritario. No imponer a los demás, cada quien aprende por sí mismo.\nEl Be'e le depara éxitos y lo mejor en su vida. Viajes y relaciones amorosas en el extranjero.", "cruz14"),
("Kan", "No'j", "Kawoq", "B'atz'", "Aj", "La persona nacida ante el día KAN es engendrada en NO’J y su destino lo rige el día AJ. El signo del KAN es uno de los signos más respetados. Es un ser noble, aunque tiene que cuidar su orgullo, pues esta es su debilidad.\nEl No'j, le proporciona nobleza, idealismo e inteligencia. El conocimiento y la sed de aprendizaje es su mayor prueba, necesita ponerlo en práctica para alcanzar esa sabiduría que anhela.\nEl Kawoq en su lado derecho le da una vida familiar muy enriquecedora, pero que puede crear una codependencia. Necesita superar ésta para volar por sí mismo.\nEl B'atz', como energía de su lado izquierdo, le permite ser reconocido como una autoridad. Puede ser un consejero en el campo intelectual, psicológico y espiritual.\nEl Aj, le da una relación con la Madre Tierra muy especial. De edad mayor, alcanza su verdadero poder y conocimiento.", "cruz15"),
("Keme", "Tijax", "Ajpu", "Be'e", "I'x", "La persona nacida ante el día KEME es engendrada en el día TIJAX y su destino lo rige el día I’X. El signo KEME le trae a la persona una inagotable fuente de protección. Prepara el campo para la vida futura, aunque no sea consciente de esto.\nEl Tijax lo protege, lo retirará de cualquier situación o persona que le traiga problemas. Es el cuchillo de doble filo que rasga el velo de los misterios.\nEl Ajpu en su lado derecho, le pone pruebas a lo largo de la vida de las cuales siempre sale adelante.\nEl Be'e en su lado izquierdo le da buena proyección para desarrollar sus proyectos y le hace ser una autoridad espiritual.\nEl I'x, le dará una vida intensa, llena de altibajo, aunque siempre se le reconocerá como autoridad.", "cruz16"),
("Kiej", "Kawoq", "Imox", "Aj", "Tz'ikin", "La persona nacida ante el día KIEJ es engendrada en KAWOQ y su destino lo rige el día TZ’IKIN. Tiene que dar atención a la armonía, el arte, la belleza, sino difícilmente encontrará la felicidad. Necesita el contacto con la naturaleza para su evolución.\nEl Kawoq, le brinda oportunidades y abundancia si la sabe conservar y no despilfarrar. Necesita la protección y la seguridad de su hogar.\nEl Imox, en su lado derecho, orienta su vida al arte y a una búsqueda de la belleza y la armonía y lo hace más flexible en la vida. Este signo le hace hacer cosas inusuales. La persona puede desarrollar fácilmente su intuición.\nEl Aj, en su lado izquierdo, le da buena fortuna, le trae muchas oportunidades y relaciones con el extranjero, donde encontrará el desarrollo espiritual. Será reconocido como autoridad.\nEl Tz'ikin, es la fuerza que le da verdadera suerte, fortuna y protección, y le hará sobresalir a lo largo de la vida.", "cruz17"),
("Q'anil", "Ajpu", "Iq'", "I'x", "Ajmaq", "La persona nacida ante el día Q’ANIL es engendrada en AJPU’ y su destino lo rige AJMAQ. Busca la tranquilidad y la armonía. Todo lo que inicie tendrá éxito, lento pero seguro.\nEl Ajpu en la concepción le da poder, un don de servicio y ayuda a los demás. Vencerá los obstáculos en su camino, y poco a poco logrará la confianza en sí mismo.\nEl Iq' en su lado derecho lo hace soñador y de fácil entendimiento, sensitivo y de buena imaginación. Muy afectado por la Luna.\nLa energia del I'x, que le trae dignidad y responsabilidad en todo lo que emprende, la fuerza para terminar con lo que no le conviene. Será reconocida la labor que realiza. Debe solucionar sus propias necesidades antes de ayudar a los demás.\nLa energia del Ajmaq, es el que más influye en su futuro, le da cambios y le da una inclinación hacia la espiritualidad. Ajmaq es la curiosidad, le impulsa a mundos desconocidos.", "cruz18"),
("Toj", "Imox", "Aq'ab'al", "Tz'ikin", "No'j", "La persona nacida ante el día TOJ es engendrada en IMOX y su destino lo rige el día NO’J. Este signo le da un poder especial para desarrollar su fuerza interior, debe utilizar ese poder para fines positivos y no despilfarrar en cosas negativas.\nEl Imox, le trae buena dosis de sensibilidad y excentricidad; desarrolla su intuición y revelaciones por medio de los sueños. Buena relación con el agua.\nEl Aq'ab'al, en su lado derecho, le hará parecer físicamente más joven de lo que en realidad es y le da una visión futurista. Muchas oportunidades a lo largo de su vida.\nvEl Tz'ikin, en su lado izquierdo, le da una energía extra que lo hará parecer inagotable. Contará con una buena posición social y fortuna.\nEl No'j (conocimiento y sabiduría), hará de su vida una experiencia maravillosa y digna.", "cruz19"),
("Tz'i'", "Iq'", "Kat", "Ajmaq", "Tijax", "La persona nacida ante el día TZ’I’ es engendrada en IQ’ y su destino lo rige TIJAX. Traen beneficio y prosperidad a la comunidad. Afortunado en el amor, aunque puede cambiar fácilmente sus relaciones.\nEl Iq', le da mucha imaginación, a veces no hace diferencia entre su imaginación y la realidad. Debe orientar esta cualidad al arte. Fuerte influencia de la Luna.\nEl K'at (la red), en su lado derecho, le trae enredos. Debe aprender a no dirigir la vida de los demás, así esta red le servirá para conseguir lo que quiere.\nEl Ajmaq, en su lado izquierdo, lo acerca a la espiritualidad y desarrolla la visión, la intuición y le da dotes de profetas. Le trae prestigio y buena posición tanto en lo social como en lo económico.\nLa energia de su destino, Tijax, le ayuda a retirar todo lo que pueda harcerle daño o sombra en su camino. Le da el poder de cortar cualquier energía negativa.", "cruz20")
;